// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxH-BFLiZXB-GaEG7_6nBDbv68ComtPQ',
    appId: '1:678422519746:web:b68d8780a4211f0bac405b',
    messagingSenderId: '678422519746',
    projectId: 'ldsw-37-integracion-bd',
    authDomain: 'ldsw-37-integracion-bd.firebaseapp.com',
    storageBucket: 'ldsw-37-integracion-bd.firebasestorage.app',
    measurementId: 'G-5P31NNVEPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjIc-w5Ph9_9SfVMdAouWdpN-DjKtIw7Y',
    appId: '1:678422519746:android:a88bb30fb86ec8f2ac405b',
    messagingSenderId: '678422519746',
    projectId: 'ldsw-37-integracion-bd',
    storageBucket: 'ldsw-37-integracion-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVKj0nm15KQc4Q2aZ-BXjzvyy7BboIXH0',
    appId: '1:678422519746:ios:069b89e7c43ca60eac405b',
    messagingSenderId: '678422519746',
    projectId: 'ldsw-37-integracion-bd',
    storageBucket: 'ldsw-37-integracion-bd.firebasestorage.app',
    iosBundleId: 'com.example.ldsw36PetiionesHttp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVKj0nm15KQc4Q2aZ-BXjzvyy7BboIXH0',
    appId: '1:678422519746:ios:069b89e7c43ca60eac405b',
    messagingSenderId: '678422519746',
    projectId: 'ldsw-37-integracion-bd',
    storageBucket: 'ldsw-37-integracion-bd.firebasestorage.app',
    iosBundleId: 'com.example.ldsw36PetiionesHttp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlxH-BFLiZXB-GaEG7_6nBDbv68ComtPQ',
    appId: '1:678422519746:web:3567e1a9c5ee07a9ac405b',
    messagingSenderId: '678422519746',
    projectId: 'ldsw-37-integracion-bd',
    authDomain: 'ldsw-37-integracion-bd.firebaseapp.com',
    storageBucket: 'ldsw-37-integracion-bd.firebasestorage.app',
    measurementId: 'G-KLFGMZRKKY',
  );
}
